apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linka-staging

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: linka-frontend
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "https://staging.selinka.ufc.br/api/v1"
    target:
      kind: Deployment
      name: linka-frontend

images:
  - name: linka-frontend
    newTag: develop
